// <auto-generated />
using System.Windows.Controls;

namespace ProcureDevelopment.Audit.Wpf.Views
{
    /// <summary>
    ///     Interaction logic for BuilderMtView.xaml
    /// </summary>
    public partial class BuilderMtView : UserControl
    {
        public BuilderMtView()
        {
            this.InitializeComponent();
        }
    }
}