// <auto-generated />
using System.Windows.Controls;

namespace BrookfieldResidentialProperties.Audit.Wpf.Views
{
    /// <summary>
    ///     Interaction logic for ConfigurationView.xaml
    /// </summary>
    public partial class ConfigurationView : UserControl
    {
        public ConfigurationView()
        {
            this.InitializeComponent();
        }
    }
}