// <auto-generated />
using System.Windows.Controls;

namespace ProcureDevelopment.Audit.Wpf.Views
{
    /// <summary>
    ///     Interaction logic for RunView.xaml
    /// </summary>
    public partial class RunView : UserControl
    {
        public RunView()
        {
            InitializeComponent();
        }
    }
}