// <auto-generated />

namespace BrookfieldResidentialProperties.Audit.Wpf.Views
{
    using System.Windows.Controls;

    /// <summary>
    ///     Interaction logic for SageView.xaml
    /// </summary>
    public partial class SageView : UserControl
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="SageView" /> class.
        /// </summary>
        public SageView()
        {
            this.InitializeComponent();
        }
    }
}