// <auto-generated />
using System.Windows;

namespace ProcureDevelopment.Audit.Wpf
{
    /// <summary>
    ///     Interaction logic for App.xaml
    /// </summary>
    public partial class App : Application
    {
    }
}